# Generated by Django 2.2 on 2019-09-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190924_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teaching_subject',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
