# Generated by Django 2.2 on 2019-09-28 10:20

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_teaching_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teacher_certificate',
            field=models.FileField(default=None, upload_to=account.models.certificate_file_path),
            preserve_default=False,
        ),
    ]
