# Generated by Django 2.2 on 2019-09-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190928_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='teacher_certificate',
            new_name='teaching_certificate',
        ),
    ]
