# Generated by Django 2.2 on 2019-10-01 12:18

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190928_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=40)),
                ('main_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MainClass')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('pdf', models.FileField(upload_to=account.models.Lesson.pdf_upload_path)),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SubClass')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.MainClass'),
        ),
    ]
