# Generated by Django 2.2 on 2019-11-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191001_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='main_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.MainClass'),
        ),
    ]
