# Generated by Django 2.2 on 2020-01-06 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191210_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
