# Generated by Django 2.2 on 2020-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200107_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='color_code',
            field=models.CharField(default='C70000', max_length=6),
        ),
    ]
