# Generated by Django 2.2 on 2020-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_lesson_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='color_code',
        ),
        migrations.AddField(
            model_name='subclass',
            name='color_code',
            field=models.CharField(default='C70000', max_length=6),
        ),
    ]
