# Generated by Django 2.2 on 2020-01-11 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200108_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Userprofile')),
                ('subclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.SubClass')),
            ],
        ),
    ]
