# Generated by Django 2.2 on 2020-01-19 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200111_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='date',
        ),
        migrations.AddField(
            model_name='grade',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
