# Generated by Django 2.2 on 2020-02-23 15:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200119_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_term_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_certificate',
            field=models.FileField(null=True, upload_to=account.models.certificate_file_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
