# Generated by Django 2.2 on 2020-02-25 13:12

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200223_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('topics', models.FileField(blank=True, null=True, upload_to=account.models.Event.test_pdf_upload_path)),
                ('sub_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SubClass')),
            ],
        ),
    ]
