# Generated by Django 2.2 on 2020-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_upcomingtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtest',
            name='event_type',
            field=models.CharField(choices=[('test', 'Test'), ('project', 'Project'), ('homework', 'Homework')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
