# Generated by Django 2.2 on 2020-03-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200302_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingtest',
            name='event_type',
        ),
    ]
