# Generated by Django 2.2 on 2020-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_upcomingtest_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtest',
            name='event_type',
            field=models.CharField(choices=[('test', 'Test'), ('project', 'Project'), ('homework', 'Homework')], max_length=10, null=True),
        ),
    ]
