# Generated by Django 2.2 on 2020-03-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_upcomingtest_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingtest',
            name='topics',
        ),
    ]
