# Generated by Django 2.2 on 2020-03-02 15:48

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_upcomingtest_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('event_type', models.CharField(choices=[('test', 'Test'), ('project', 'Project'), ('homework', 'Homework')], max_length=10, null=True)),
                ('topics', models.FileField(blank=True, null=True, upload_to=account.models.Event.test_pdf_upload_path)),
                ('sub_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SubClass')),
            ],
        ),
        migrations.DeleteModel(
            name='UpcomingTest',
        ),
    ]
