# Generated by Django 2.2 on 2020-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='subject',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
