# Generated by Django 2.2 on 2020-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20200312_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='subclass_color_code',
            field=models.CharField(default='C70000', max_length=6),
        ),
        migrations.AddField(
            model_name='request',
            name='subclass_name',
            field=models.CharField(default='giani', max_length=30),
            preserve_default=False,
        ),
    ]
