# Generated by Django 2.2 on 2020-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20200312_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='subclass_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
