# Generated by Django 2.2 on 2020-03-15 14:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_remove_request_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_certificate',
            field=models.FileField(blank=True, null=True, upload_to=account.models.certificate_file_path),
        ),
    ]
