# Generated by Django 2.2 on 2020-03-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20200315_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='subclass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SubClass'),
        ),
    ]
