# Generated by Django 2.2 on 2020-03-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_request_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='subclass',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SubClass'),
        ),
    ]
