# Generated by Django 2.2 on 2020-03-19 10:09

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20200316_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('archive_type', models.CharField(choices=[('submission', 'Submission'), ('private', 'Private')], default='private', max_length=30)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=account.models.Archive.pdf_upload_archive_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Userprofile')),
                ('sub_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SubClass')),
            ],
        ),
    ]
